import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import { Providers } from "@/providers";
import { menus } from "@/types/common";
import { dehydrate, HydrationBoundary, QueryClient } from "@tanstack/react-query";
import { fetchUser } from "@/lib/user";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryKey: ["user"],
    queryFn: () => fetchUser(),
  });
  return (
    <html lang="en">
      <body className={`bg-gray-500 antialiased`}>
        <Providers>
          <HydrationBoundary state={dehydrate(queryClient)}>

      
          <div className="flex px-40 py-40">
            <Sidebar
              brand="Mark"
              menus={menus}
            />
            <div className="bg-gray-100 min-h-[50vh] w-full -ml-15 rounded-4xl p-5">
              {children}
            </div>
          </div>
              </HydrationBoundary>
        </Providers>
      </body>
    </html>
  );
}
