import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import { Providers } from "@/providers";
import { menus } from "@/types/common";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gray-500 antialiased`}>
        <Providers>
          <div className="flex px-40 py-40">
            <Sidebar
              brand="Mark"
              menus={menus}
            />
            <div className="bg-gray-100 min-h-[50vh] w-full -ml-15 rounded-4xl p-5">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
